Repository cse110-fa22-group2/team2-fa22-cse110, pull requests merged in 2022-12, with the labels that each got.

#74 Meeting notes
  admin/meetings/112822-sprint-2-review.md
  admin/meetings/120222-team_progress6.md
Labels: documentation, front end, back end, testing

#92 Add backend functions that support several features
  .github/workflows/ci.yml
  doc/dict.js.html
  doc/fonts/OpenSans-Bold-webfont.eot
  doc/fonts/OpenSans-Bold-webfont.svg
  doc/fonts/OpenSans-Bold-webfont.woff
  doc/fonts/OpenSans-BoldItalic-webfont.eot
  doc/fonts/OpenSans-BoldItalic-webfont.svg
  doc/fonts/OpenSans-BoldItalic-webfont.woff
  doc/fonts/OpenSans-Italic-webfont.eot
  doc/fonts/OpenSans-Italic-webfont.svg
  doc/fonts/OpenSans-Italic-webfont.woff
  doc/fonts/OpenSans-Light-webfont.eot
  doc/fonts/OpenSans-Light-webfont.svg
  doc/fonts/OpenSans-Light-webfont.woff
  doc/fonts/OpenSans-LightItalic-webfont.eot
  doc/fonts/OpenSans-LightItalic-webfont.svg
  doc/fonts/OpenSans-LightItalic-webfont.woff
  doc/fonts/OpenSans-Regular-webfont.eot
  doc/fonts/OpenSans-Regular-webfont.svg
  doc/fonts/OpenSans-Regular-webfont.woff
  doc/global.html
  doc/index.html
  doc/scripts/linenumber.js
  doc/scripts/prettify/Apache-License-2.0.txt
  doc/scripts/prettify/lang-css.js
  doc/scripts/prettify/prettify.js
  doc/styles/jsdoc-default.css
  doc/styles/prettify-jsdoc.css
  doc/styles/prettify-tomorrow.css
  out/dict.js.html
  out/global.html
  out/index.html
  package-lock.json
  package.json
  source/test/dict.test.js
Labels: bug, documentation, enhancement, back end, testing

#90 adding frontend meeting notes from today
  admin/meetings/120622-frontend_meetings7.md
Labels: documentation

#95 Fix E2E tests
  source/test/e2e.test.js
Labels: devops, testing

#96 Updated e2e testing
  doc/dict.js.html
  source/test/e2e.test.js
Labels: devops

#99 Merge dev to main for final video
  source/test/dict.test.js
Labels: devops, testing

#101 Update README.md
  README.md
Labels: documentation, devops

#103 removed deleted branches pipeline
  .github/workflows/ci.yml
Labels: documentation, devops
