Repository cse110-fa22-group2/team2-fa22-cse110, pull requests merged in 2022-11, with the labels that each got.

#6 Pushing the meeting notes from 11/01 to main branch.
  admin/meetings/110122-begin_project_assignments.md
Labels: documentation

#9 adding meeting notes from frontend team meeting
  admin/images/frontend_milestone1_get_cards.png
  admin/meetings/110122-begin_project_assignments.md
  admin/meetings/110422-frontend_meeting.md
  admin/meetings/110622-frontend_meeting.md
Labels: documentation, front end

#10 updating meeting notes session 1 and 2 to include time
  admin/meetings/110422-frontend_meeting.md
  admin/meetings/110622-frontend_meeting.md
Labels: documentation, front end

#8 Added a workflow for an HTML Validator
  .github/workflows/validate.yml
  source/actionsLogs/log.log
  source/test.html
Labels: devops, testing

#25 Deployed Web App to Netlify
  .github/workflows/pipeline.yml
  source/index.html
Labels: devops

#30 Ci/cd testing
  .github/workflows/pipeline.yml
Labels: devops

#33 Js docs
  .eslintrc.js
  .github/workflows/pipeline.yml
  .gitignore
  README.md
  package-lock.json
  package.json
  source/actionsLogs/log.log
  source/index.html
  source/testeslint.js
Labels: documentation, devops

#35 Js docs
  .github/workflows/pipeline.yml
  source/testeslint.js
Labels: documentation, devops

#36 Unit testing
  .github/workflows/ci.yml
  package-lock.json
  package.json
  source/sum.js
  source/sum.test.js
Labels: devops, testing

#40 Cleaned up ci.yml and added jest support for linting
  .eslintrc.js
  .github/workflows/ci.yml
  source/actionsLogs/log.log
  source/sum.js
  source/sum.test.js
  source/testeslint.js
Labels: documentation, devops

#44 Update phase1.md
  admin/cipipeline/phase1.md
Labels: documentation, devops

#45 add website logo image & update meeting notes (more than one)
  admin/images/d_logo.png
  admin/meetings/110422-frontend_meeting1.md
  admin/meetings/110622-frontend_meeting2.md
  admin/meetings/110822-team_progress1.md
  admin/meetings/111022-team_progress2.md
  admin/meetings/111122-frontend_meeting3.md
  admin/meetings/111322-frontend_meeting4.md
  admin/meetings/111422-team_progress3.md
  admin/team.md
Labels: documentation

#51 Added initial E2E testing
  .github/workflows/ci.yml
  .gitignore
  package-lock.json
  package.json
  source/src/components/tinyMCE/tiny-mce.css
  source/src/components/tinyMCE/tiny-mce.html
  source/test/e2e.test.js
Labels: devops, testing

#53 Integrated search form backend. Added opening a term.
  .eslintrc.js
  package-lock.json
  package.json
  source/.gitkeep
  source/create-term.html
  source/home.html
  source/search.html
  source/src/backend/dict.js
  source/src/common-scripts/redirection.js
  source/src/components/confirmation-box/confirmation-box.css
  source/src/components/term-card/term-card.html
  source/src/components/term-card/term-card.js
  source/src/components/tinyMCE/tiny-mce.html
  source/src/pages/create-term/create-term.js
  source/src/pages/home/home.css
  source/src/pages/home/home.js
  source/src/pages/search/search.css
  source/src/pages/search/search.js
  source/src/pages/term-page/term-page.css
  source/src/pages/term-page/term-page.js
  source/term-page.html
  source/test.html
Labels: front end, back end

#41 Backend
  .eslintrc.js
  source/src/backend/dict.js
  source/src/common-scripts/redirection.js
  source/src/components/term-card/term-card.js
Labels: back end

#72 Update e2e.test.js
  source/test/e2e.test.js
Labels: devops

#73 Sprint + Retro meeting notes
  admin/meetings/102522-starting_pitch.md
  admin/meetings/112822-retrospective.md
  admin/meetings/112822-sprint-2-review.md
Labels: documentation, devops, front end, back end
